### ISSUE TITLE
MailPoet Sign-Up confirmation emails are not logged

### ISSUE THREAD

**Issue by rafaehlers** [awesomemotive/wp-mail-logging#114]
From HS: https://secure.helpscout.net/conversation/1122074893/198890/

```This is a feature request:
I'm using both MailPoet + WP Mail Logging on my site. Great set of features!

Unfortunately WP Mail Logging does not show the "double opt-in" mails sent to the users. Can you please include those with a future release?
```

**Comment by donmhico** [comment]
@rafaehlers - Thank you for creating this issue. I'll be closing this issue due to the lack of activity. However, I believe that the reason why the "double opt-in" isn't logged is that those emails were either sent by the MailPoet service (from their servers) or if they were sent via WordPress, they weren't sent via `wp_mail()` function. I believe it's the former.
