### ISSUE TITLE
Mails do not arrive :-/

### ISSUE THREAD

**Issue by TodayisPhenomenal** [awesomemotive/wp-mail-logging#156]
Hi WP  mail team,

we have a huge issue... Everything seems to be set up as it should  and despite this we see that our mails are not being received. Both internal communications as mails to our customers.

Please help us out. We are a non profit organization - good cause - with limited capabilities
![Picture1](https://user-images.githubusercontent.com/128134013/225857163-5c88424f-9372-4d42-a5ec-af18f3763f92.png)
![Picture2](https://user-images.githubusercontent.com/128134013/225857304-9b73137d-6943-4e0f-ae8d-f93a2fafec8b.png)
 
![Picture3](https://user-images.githubusercontent.com/128134013/225857498-eb21c374-e5fe-4380-b341-3e231bef6379.png)

**Comment by capuderg** [comment]
Hi @TodayisPhenomenal,

this plugin does not improve email deliverability, it just logs the emails that are sent out from your WordPress site. 

There are a lot of steps that emails have to make in order to be delivered to the recipient’s inbox.

When your WordPress site sends an email, there’s no guarantee it will be delivered.

This is what the email’s journey looks like:

1. WordPress creates an email
2. WordPress passes the email to your website host and that email gets logged by our plugin
3. The host server takes the email and sends it (SMTP or Mail Transfer Agent)
4. Recipient server receives or blocks the email
5. If the email is accepted, the spam filter decides if it goes to the inbox or the spam folder
6. Recipients see the email and might open it.

This plugin does not track delivery after step 2.

I would recommend installing and configuring one of the mailers in the [WP Mail SMTP](https://wordpress.org/plugins/wp-mail-smtp/) plugin (free plugin). This will actually resolve your email deliverability issues.

Take care!
