### ISSUE TITLE
Give access to WP Mail Log for specific user

### ISSUE THREAD

**Issue by githubyaya** [awesomemotive/wp-mail-logging#97]
We are using WP Mail Log - its a great plugin, thank you for that!

We have a customer support team who have restricted access to our WP Backend. We would like them to have access to WP Mail Log, to be able to use the email history to help specific clients. However, as we have restricted Capabilites for this particular User Role in WP, unfortunately our customer service cannot see WP Mail Log in the WP Admin meny from the backend.

When looking at all Roles that can be enabled or disabled in WP, there are many plugins that have defined roles particular for that plugin. But for WP Mail Log, we cannot find any user roles that seems to be defined specifically for this plugin. Therefore, we struggle to give our customer sopport access to the WP Mail Log, without giving them access to "everything". 

Would you consider building functionality such that granting granular access to this plugin would be possible when setting up WP users and roles?

I am happy to provide screen shots or more info if required.

With kind regards/Fredrik

**Comment by donmhico** [comment]
@githubyaya - Thanks for creating this issue. What @No3x mentioned in his last comment is correct. You can create a new or assign an existing capability to a user then set this capability in Dashboard -> WP Mail Logging -> Settings -> Can See Submission Data to allow access to WP Mail Logging logs to a specific user(s).

https://a.supportally.com/i/2X9LCA

I'm closing this issue as the original question was answered and there are no new activity in this issue since then.
